### PR TITLE
improve prettier configs and format files

### PR DESCRIPTION
**Pull request by with-heart**
This PR makes a few changes in order to clean up the repo a bit:

- removed `"prettier": {}` from `package.json` to make sure we're all formatting with `.prettierrc`
- replaced `source.organizeImports` in `.vscode/settings.json` with `prettier-plugin-organize-imports` so all contributors have their imports organized
- added a `pre-commit` hook for `husky`. we already had it installed and `lint-staged` configs exist in `package.json`, we just didn't have a hook to actually do anything with them
- widened `lint-staged` to target `*` files and added the `--ignore-unknown` flag, so now all files recognized by `prettier` will be formatted on commit
- formatted all files with `prettier`

It basically felt like every file I touched ended up with a bunch of unrelated formatting changes, so this should resolve that issue for everyone moving forward.

### CODE REVIEW

**Comment by davidkpiano** [comment]
@with-heart This is great, thank you! Can you resolve the merge conflict?

**Comment by with-heart** [comment]
@davidkpiano Ye! Will fix that and ci failures today

**Comment by Andarist** [comment]
This will end up in lots of conflicts with my ongoing work. I'd like to land this but perhaps once I manage to land my stuff on the main branch, then this could land and I could branch out from a clean main.

**Comment by with-heart** [comment]
> This will end up in lots of conflicts with my ongoing work. I'd like to land this but perhaps once I manage to land my stuff on the main branch, then this could land and I could branch out from a clean main.

Yeah, that's totally fair! There's no rush and config stuff is far less important than actual work

**Comment by Andarist** [comment]
@with-heart I'd prefer to revert the "organize imports" change from this PR. I feel like this is just nice to have but it slows down the whole thing quite a bit as this plugin creates a language service per file.

**Comment by with-heart** [comment]
@Andarist That works! Will revert and also rebase in just a sec

**Pull request merged**
