### PR TITLE
Revert @babel/core changes

### PR DESCRIPTION
**Pull request by mattpocock**

### CODE REVIEW

**Comment by Andarist** [comment]
@mattpocock could you comment on why this is needed and what kind of problems did this create? It's far from obvious now ;p

**Comment by mattpocock** [comment]
@Andarist Looks like this makes the VSCode parsing fail on some machines:

#96

**Comment by Andarist** [comment]
Do we have any more info about this or a repro case? The issue only mentions problems with finding the prettier module.

**Comment by Andarist** [comment]
Could we perhaps gather more info? maybe release additional logs etc?  If we add those now they might both help us fix this and also help us diagnose future issues.

**Comment by mattpocock** [comment]
@Andarist I think probably we should revert this change first (since it's an urgent fix for prod and we know it works) then investigate.

**Comment by Andarist** [comment]
If we revert without investigating first... how do we investigate this later?

**Comment by Andarist** [comment]
Either way - It's your call and I will totally respect your decision here. But there is a missing test case here (although it's dependent on the Babel implementation) that we are missing and we might weirdly end up with the same problem somehow in the future

**Comment by mattpocock** [comment]
@Andarist Yep, I can see that. I think I'd prefer to know it's fixed than wonder why it's broken.

**Comment by mattpocock** [comment]
@Andarist Actually, ignore above, I've managed to reproduce using MDPratt's machine

**Pull request closed without merging**
